### ISSUE TITLE
powermail 8.2.4 support

### ISSUE THREAD

**Issue by MicrosoftAlternative** [in2code-de/invisiblerecaptcha#17]
When using invisiblerecaptcha 5.0.0 with powermail 8.2.4 on typo3 10.4.10, the parsley.js doesn't seem to work with the reCaptcha.

**Comment by agendartobias** [comment]
I get an error Uncaught (in promise) null - anchor?

**Comment by abvdveen** [comment]
I can confirm that using this pull request fixes my powermail forms using inviseble recaptcha on a Typo3 10.4.31 setup.

**Comment by pixeldesu** [comment]
While this talks about another issue, the titled Powermail 8.2 support is already present. Parsley isn't used in Powermail either anymore.
